import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { useAuth } from "./AuthContext";

const LANGUAGE_STORAGE_KEY = "judgify_language";

export const supportedLanguages = [
  { code: "en", label: "EN", name: "English" },
  { code: "uk", label: "UA", name: "Українська" },
];

const dictionaries = {
  en: {
    splash: {
      starting: "Starting backend and database...",
      loadingDemo: "Loading demo competitions...",
      waitingApi: "Waiting for API connection...",
    },
    header: {
      goHome: "Go to landing page",
      search: "Search",
      language: "Language",
      signUp: "Sign Up",
      signIn: "Sign In",
      profile: "Profile",
    },
    auth: {
      close: "Close",
      signUpTitle: "Sign Up",
      username: "Username",
      usernamePlaceholder: "Enter your username",
      emailAddress: "Email address",
      email: "Email",
      emailPlaceholder: "Enter your email address",
      password: "Password",
      passwordPlaceholder: "Password",
      createPassword: "Create your password",
      confirmPassword: "Confirm your password",
      confirmPasswordLabel: "Confirm your password",
      togglePassword: "Toggle password visibility",
      showPassword: "Show",
      hidePassword: "Hide",
      rolePrompt: "I want to join as:",
      chooseRole: "Choose account role",
      alreadyHaveAccount: "Already have an account?",
      logIn: "Log In",
      welcomeBack: "Welcome back",
      signInCaption: "Sign in to manage saved competitions, applications and organizer tools.",
      signingIn: "Signing in...",
      signInAction: "Sign in",
      or: "OR",
      continueOrganizerDemo: "Continue as organizer demo",
      continueAdminDemo: "Continue as administrator demo",
      noAccount: "No account yet?",
      createAccount: "Create account",
      fillRequired: "Please fill in all required fields.",
      passwordsMismatch: "Passwords do not match.",
      enterEmailPassword: "Enter email and password.",
    },
    onboarding: {
      title: "Tell us more",
      subtitle: "Choose your interests",
      secondary: "You can update this later in your profile.",
      interests: "Interests",
      interestPlaceholder: "Type interest and press Enter",
      createTeam: "Create team after registration",
      continue: "Continue",
    },
    roles: {
      organizer: "Organizer",
      participant: "Participant",
      viewer: "Viewer",
      admin: "Administrator",
      administrator: "Administrator",
      team_member: "Team member",
    },
    options: {
      status: {
        active: "Online",
        draft: "Draft",
        published: "Published",
        finished: "Finished",
        judging: "Judging",
        archived: "Archived",
        registration_open: "Registration open",
        upcoming: "Upcoming",
        pending: "Pending",
        approved: "Approved",
        rejected: "Rejected",
        withdrawn: "Withdrawn",
        scheduled: "Scheduled",
        closed: "Closed",
        judged: "Judged",
      },
      event_type: {
        online: "Online",
        offline: "Offline",
        hybrid: "Hybrid",
      },
      participation_type: {
        individual: "Individual",
        team: "Team",
        mixed: "Mixed",
      },
      industry: {
        programming: "Programming",
        design: "Design",
        robotics: "Robotics",
        cybersecurity: "Cybersecurity",
        ai: "AI",
        data_science: "Data Science",
        web: "Web",
        mobile: "Mobile",
      },
      difficulty: {
        beginner: "Beginner",
        intermediate: "Intermediate",
        advanced: "Advanced",
        mixed: "Mixed",
      },
      language: {
        uk: "Ukrainian",
        en: "English",
        pl: "Polish",
        de: "German",
        fr: "French",
        es: "Spanish",
        other: "Other",
      },
      access_mode: {
        open: "Open registration",
        application: "Application review",
        invite_only: "Invite only",
      },
      visibility_mode: {
        public: "Public catalog",
        unlisted: "Unlisted link",
        private: "Private",
      },
      submission_mode: {
        file_upload: "File upload",
        text_answer: "Text answer",
        repository_link: "Repository link",
        demo_link: "Demo link",
        mixed: "Mixed",
      },
      material_type: {
        rules: "Rules",
        dataset: "Dataset",
        template: "Template",
        guide: "Guide",
        other: "Other",
        file: "File",
      },
      review_type: {
        automatic: "Automatic",
        jury: "Jury",
        manual: "Manual",
        peer: "Peer review",
        peer_review: "Peer review",
        participant: "Participant",
      },
      aggregation: {
        average: "Average",
        sum: "Sum",
      },
      visibility: {
        aggregate: "Aggregate",
        open: "Open",
        anonymous: "Anonymous",
      },
    },
    account: {
      currentUser: "Current user",
      user: "User",
      openProfile: "Open profile",
      adminPanel: "Admin panel",
      switchAccount: "Switch account",
      signOut: "Sign out",
      accountMenu: "Account menu",
    },
      admin: {
        title: "Admin panel",
        subtitle: "Manage accounts, competitions, landing filters and server performance.",
      tabs: {
        users: "Accounts",
        competitions: "Competitions",
        filters: "Landing filters",
        server: "Server",
      },
      actions: "Actions",
      delete: "Delete",
      settings: {
        title: "Platform settings",
        subtitle: "Control administrative automation for organizer requests.",
        autoApproveOn: "Auto-approve organizer requests: on",
        autoApproveOff: "Auto-approve organizer requests: off",
      },
      stats: {
        users: "Users",
        activeUsers: "Active users",
        competitions: "Competitions",
        pendingCompetitions: "Pending approvals",
        activeCompetitions: "Active competitions",
        draftCompetitions: "Drafts",
      },
      users: {
        title: "Accounts",
        search: "Search users",
        allRoles: "All roles",
        user: "User",
        role: "Role",
        status: "Status",
        staff: "Staff",
        activity: "Activity",
        active: "Active",
        inactive: "Inactive",
        staffYes: "Staff",
        staffNo: "No",
        competitions: "{count} competitions",
        requests: "{count} requests",
        empty: "No accounts found.",
        confirmDelete: "Delete account \"{name}\"? This cannot be undone.",
      },
      competitions: {
        title: "Competitions",
        search: "Search competitions",
        allStatuses: "All statuses",
        competition: "Competition",
        status: "Status",
        approval: "Approval",
        visibility: "Visibility",
        catalog: "Catalog",
        results: "Results",
        noOrganizer: "No organizer",
        shown: "Shown",
        hidden: "Hidden",
        frozen: "Frozen",
        open: "Open",
        empty: "No competitions found.",
        confirmDelete: "Delete competition \"{name}\"? This cannot be undone.",
      },
      filters: {
        title: "Landing filters",
        subtitle: "Edit labels or hide options. Values stay locked so existing competitions keep working.",
        group: "Group",
        value: "Value",
        labelEn: "English label",
        labelUk: "Ukrainian label",
        order: "Order",
        visibility: "Visibility",
        visible: "Visible",
        hidden: "Hidden",
        empty: "No filter options found.",
        newValue: "New value",
        add: "Add filter",
      },
      server: {
        title: "Server performance",
        waiting: "Waiting for metrics...",
        refresh: "Refresh",
        uptime: "Uptime",
        uptimeDays: "{days}d {hours}h",
        uptimeHours: "{hours}h {minutes}m",
        uptimeMinutes: "{minutes}m",
        databaseLatency: "DB latency",
        processMemory: "Process memory",
        memoryUsed: "Memory used",
        diskUsed: "Disk used",
        loadAverage: "Load average",
        platform: "Platform",
        python: "Python",
        django: "Django",
        cpu: "CPU cores",
        memory: "Memory",
        disk: "Disk",
      },
      messages: {
        create: "Create mailing",
        recent: "Recent mailings",
        targetRole: "Target role",
        manualRecipients: "Manual recipients",
        allUsers: "All active users",
        competition: "Competition",
        noCompetition: "No competition",
        status: "Status",
        queued: "Queued",
        draft: "Draft",
        recipientsPlaceholder: "email1@example.com, email2@example.com",
        subject: "Subject",
        body: "Body",
        general: "General",
        empty: "No mailings yet.",
      },
      saving: "Saving...",
    },
    filters: {
      title: "Filters:",
      groups: {
        status: "Status",
        event_type: "Event type",
        participation_type: "Participation type",
        industry: "Industry",
        difficulty: "Difficulty",
        language: "Language",
        access_mode: "Access mode",
      },
      status: "Competition status:",
      eventType: "Tournament type:",
      participationType: "Type of participation:",
      industry: "Industry:",
      difficulty: "Difficulty:",
      language: "Language:",
      reset: "Reset Filters",
    },
    landing: {
      loading: "Loading...",
    },
    sidebar: {
      recentlyViewed: "Recently Viewed",
      emptyRecent: "No recently viewed items yet.",
      competitions: "Competitions",
      materials: "Materials",
      saved: "Saved",
      emptySaved: "No saved competitions yet.",
      openCompetition: "Open {name}",
      comments: "{count} comments",
    },
    competitionHeader: {
      alreadyParticipating: "Already participating",
      pendingReview: "Pending review",
      requestRejected: "Request rejected",
      join: "Join Competition",
      round: "Round: {current}/{total}",
      team: "Team: {name} - {status}",
      edit: "Edit competition",
    },
    competitionSidebar: {
      round: "Round:",
      category: "Category:",
      dates: "Dates:",
      difficulty: "Difficulty:",
      language: "Language:",
      upcomingEvent: "Upcoming event",
      downloads: "Downloads",
    },
    joinModal: {
      title: "Join Competition",
      description: "Submit a participation request. Depending on the access model, it can be approved immediately or reviewed by organizer/administrator.",
      individual: "Individual participant",
      team: "Team participant",
      teamName: "Team name",
      teamPlaceholder: "Enter team name or create a new team",
      note: "Request note",
      notePlaceholder: "Optional note for organizer/admin",
      teamRequired: "Team name is required for team participation.",
      submitError: "Could not submit join request.",
      cancel: "Cancel",
      submitting: "Submitting...",
      joinNow: "Join now",
      submitReview: "Submit for review",
    },
    tabs: {
      active: "Active competitions",
      trending: "Trending",
      new: "New",
      open_submission: "Open Submission",
      live_stream: "Live Stream",
      completed: "Finished & archived",
    },
    detailTabs: {
      overview: "Overview",
      participants: "Participants",
      results: "Results",
      judging: "Judging",
    },
    competitionPage: {
      titleFallback: "Competition",
      loading: "Loading competition...",
      notFound: "Competition not found.",
      loadError: "Could not load the competition page.",
      schedulePending: "Schedule is being finalized",
      timerUnavailable: "timer is not available",
      categoryFallback: "Competition",
      difficultyFallback: "Mixed",
      descriptionFallback: "Competition details are being prepared by the organizer.",
      roundTimer: "Round {round} timer: {time}",
      timer: "Timer: {time}",
      notConfigured: "not configured",
      you: "You",
    },
    overviewTab: {
      liveStream: "Live stream",
      roundStream: "Round stream",
      competitionStream: "Competition stream",
      openStream: "Open stream",
      announcements: "Announcements",
      emptyAnnouncements: "No announcements yet.",
      commentPlaceholder: "Leave a comment...",
      post: "Post",
    },
    participantsTab: {
      title: "Participants",
      empty: "No registered participants yet.",
      fallback: "Participant",
    },
    resultsTab: {
      title: "Results",
      roundHistory: "Round history",
      round: "Round {round}",
      leaderboard: "Leaderboard",
      rank: "Rank",
      name: "Name",
      score: "Score",
      roundScores: "Round scores",
      scored: "{count} scored",
      scoredCriteria: "Scored criteria",
      total: "Total",
    },
    judgingTab: {
      title: "Judging",
      scoringMode: "Scoring mode:",
      aggregation: "Aggregation:",
      visibility: "Visibility:",
      mySubmissions: "My submissions",
      open: "open",
      closed: "closed",
      submissionFallback: "Submission",
      noExternalLink: "No external link",
      formTitle: "Title",
      formDescription: "Description",
      repositoryUrl: "Repository URL",
      demoUrl: "Demo URL",
      sending: "Sending...",
      submitWork: "Submit work",
      submissionSent: "Submission sent to judging.",
      submissionSaveError: "Submission could not be saved.",
      submissionUnavailable: "Submissions are available only for approved participants during an active round.",
      scoreEmpty: "Scores will appear here after submitted work is evaluated.",
      scorecard: "Scorecard",
      mode: "Mode",
      round: "Round",
      submission: "Submission",
      noAcceptedForRound: "No accepted submissions are available for this round.",
      submittedWork: "Submitted work",
      noAcceptedYet: "No accepted submissions are available for this round yet.",
      criterion: "Criterion",
      max: "Max",
      score: "Score",
      comment: "Comment",
      status: "Status",
      final: "final",
      draft: "draft",
      new: "new",
      clear: "Clear",
      saving: "Saving...",
      saveDraft: "Save draft",
      finalize: "Finalize",
      scoresFinalized: "Scores finalized.",
      draftScoresSaved: "Draft scores saved.",
      scoresSaveError: "Scores could not be saved.",
      scoreRemoved: "Score removed.",
      scoreRemoveError: "Score could not be removed.",
      judgeInvitations: "Judge invitations",
      acceptedAssignments: "{count} accepted",
      waitingForResponse: "Waiting for response",
      allRounds: "All rounds",
      acceptInvite: "Accept",
      declineInvite: "Decline",
      inviteAccepted: "Invitation accepted.",
      inviteDeclined: "Invitation declined.",
      inviteResponseError: "Invitation response could not be saved.",
      acceptInviteToScore: "Accept the judge invitation before scoring.",
      judgingWindowClosed: "Judging materials are available only during the judging window.",
      repository: "Repository",
      demo: "Demo",
      file: "File",
    },
    profile: {
      organized: "organized",
      pending: "Pending",
      archived: "Archived",
      badges: "badges",
      certificates: "certificates",
      judgeAssignments: "judge assignments",
      organizerStats: "Organizer stats",
      participantStats: "Participant stats",
      judgeWork: "Judge work",
      judgeScores: "{count} scores, {final} finalized",
      organizerTools: "Organizer tools",
      createCompetitionTitle: "Create a new competition",
      createCompetitionText: "Prepare base info, rounds, deadlines, jury roles and publication status from one workspace.",
      createCompetition: "Create competition",
      organizedCompetitions: "My organized competitions",
      noOrganized: "No organized competitions.",
      step: "Step {step}",
      approval: "approval",
      myTeams: "My teams",
      captain: "Captain: {name}",
      notAssigned: "not assigned",
      you: "you",
      makeCaptain: "Make captain",
      remove: "Remove",
      captainNote: "Only one captain is allowed. Captain rights can be transferred to another team member.",
      noCompetitions: "No competitions in this section yet.",
      latest: "Latest",
      achievement: "Personal achievement",
      noBadges: "No badges yet.",
      noCertificates: "No certificates yet.",
      registrationRequests: "Registration requests",
      creationRequests: "Competition creation requests",
      myApplications: "My pending applications",
      noPending: "No pending requests.",
      approve: "Approve",
      reject: "Reject",
      editProfile: "Edit profile",
      profilePhoto: "Profile photo",
      uploadPhoto: "Upload profile photo",
      displayName: "Display name",
      email: "Email",
      status: "Status",
      organization: "Organization",
      country: "Country",
      skills: "Skills",
      interests: "Interests",
      bio: "Bio",
      saveProfile: "Save profile",
      overview: "Overview",
      archivedTab: "Archived",
      myCompetitions: "My competitions",
      loading: "Loading profile...",
      goHome: "Go to landing page",
      search: "Search",
      nameFallback: "Name",
      close: "Close",
      edit: "Edit",
      profileSections: "Profile sections",
      registeredCompetitions: "Registered competitions",
      noRegistered: "You are not registered for active or upcoming competitions yet.",
      archivedCompetitions: "Archived competitions",
      noArchived: "No archived competitions yet.",
      viewerProfile: "Viewer profile",
      viewerText: "The viewer role keeps the workspace intentionally simple: recent views and saved public competitions.",
      savedCompetitions: "Saved competitions",
      noSaved: "No saved competitions yet.",
      recentlyViewed: "Recently viewed",
      latestNotifications: "Latest notifications",
      noNotifications: "No account notifications yet.",
      personalMaterials: "Personal materials",
      material: "Material",
      file: "File",
    },
    builder: {
      steps: {
        basics: "Basics",
        basicsHint: "Card, catalog filters and public identity",
        format: "Format & Access",
        formatHint: "Registration, review, teams and discovery",
        schedule: "Schedule & Rounds",
        scheduleHint: "Registration, competition stages and round windows",
        submissions: "Submissions & Evaluation",
        submissionsHint: "Submission rules, criteria and awards",
        publish: "Publish",
        publishHint: "Preview, validation and invitations",
      },
      defaults: {
        untitled: "Untitled competition",
        round: "Round {number}",
        quality: "Quality",
        winner: "Winner",
        invitedTeam: "Invited team",
        newCriterion: "New criterion",
        specialAward: "Special award",
      },
      status: {
        saving: "Saving draft...",
        saved: "Draft saved",
        notSaved: "Draft was not saved",
        published: "Competition published",
        notPublished: "Competition was not published",
        invitesQueued: "Invitations queued as outbound messages",
        invitesFailed: "Invitations were not queued",
        judgeAssigned: "Jury member assigned",
        judgeFailed: "Jury member was not assigned",
        materialUploaded: "Material uploaded",
        materialFailed: "Material was not uploaded",
        materialRemoved: "Material removed",
        materialRemoveFailed: "Material was not removed",
      },
      validation: {
        endAfterStart: "Competition end must be later than competition start.",
        registrationBeforeStart: "Registration cannot start after the competition starts.",
        registrationEndBeforeStart: "Registration must end no later than the competition start.",
        registrationEndAfterStart: "Registration end must be later than registration start.",
        judgingAfterCompetition: "Judging cannot start before the competition ends.",
        judgingEndAfterStart: "Judging end must be later than judging start.",
        resultsAfterJudging: "Results cannot be published before judging ends.",
        roundWithinWindow: "{label}: round must start within the competition window.",
        roundEndWithinWindow: "{label}: round must end within the competition window.",
        roundEndAfterStart: "{label}: round end must be later than round start.",
        nextRoundAfterPrevious: "{label}: next round must start after the previous round ends.",
        nextRoundEndAfterPrevious: "{label}: next round must end after the previous round ends.",
        title: "competition title",
        shortDescription: "short description",
        competitionEnd: "competition end",
        oneRound: "at least one round",
        roundEnd: "round end time",
        sharingOrInvitations: "sharing link or invitations",
      },
      topbarProfile: "Profile",
      constructor: "Competition constructor",
      saveDraft: "Save draft",
      stepOf: "Step {step} of 5",
      newCompetition: "New competition",
      heroText: "One draft is updated through the whole setup flow. The same fields feed catalog filters, cards, profile blocks and participation rules.",
      title: "Title",
      categoryIndustry: "Category / industry",
      categoryNote: "Directly used in catalog filters",
      eventType: "Event type",
      difficulty: "Difficulty",
      language: "Language",
      languageNote: "Used in landing filters",
      shortDescription: "Short description",
      fullDescription: "Full description",
      coverImage: "Cover image URL",
      bannerImage: "Banner image URL",
      registrationModel: "Registration and distribution model",
      openRegistrationText: "Join immediately creates approved participation.",
      applicationReviewText: "Join creates pending request until organizer/admin approves.",
      inviteOnlyText: "Users join through organizer invitations; hidden competitions may use private links.",
      individualText: "Each participant submits independently.",
      teamText: "Registered participants join or create teams; organizers manage the competition only.",
      mixedText: "Individual and team participation are both allowed.",
      visibility: "Visibility",
      showCatalog: "Show in catalog",
      allowSharing: "Allow sharing link",
      externalRegistration: "External registration",
      minTeam: "Min team size",
      maxTeam: "Max team size",
      participantInvites: "Participant team invites",
      organizerAssignment: "Organizer team assignment",
      scheduleRounds: "Schedule and rounds",
      scheduleText: "Competition status, timers and catalog tabs are derived from these time windows and round dates.",
      registrationStarts: "Registration starts",
      registrationEnds: "Registration ends",
      competitionStarts: "Competition starts",
      competitionStartsNote: "Optional: if empty, the competition starts when you publish it.",
      competitionEnds: "Competition ends",
      judgingStarts: "Judging starts",
      judgingEnds: "Judging ends",
      resultsPublic: "Results public at",
      rounds: "Rounds",
      delete: "Delete",
      roundTitle: "Round title",
      roundTimeTitle: "Optional for the first/next sequential round; empty start is derived on publication.",
      submissionRequired: "Submission required",
      showVideo: "Show video stream",
      streamLabel: "Stream label, e.g. Round briefing",
      streamUrl: "Stream URL: YouTube, Vimeo or Twitch",
      streamHint: "Insert one normal stream link. YouTube, youtu.be, Vimeo, Twitch channel/video links are converted to an embedded player automatically. Do not paste iframe code.",
      roundDescription: "Round description",
      addRound: "Add round",
      submissionSettings: "Submission settings",
      submissionMode: "Submission mode",
      maxFileSize: "Max file size, MB",
      maxSubmissions: "Max submissions",
      repositoryRequired: "Repository required",
      demoRequired: "Demo required",
      materials: "Competition materials",
      materialTitle: "Material title",
      materialPlaceholder: "Rules, starter kit, dataset",
      materialType: "Material type",
      uploadFile: "Upload file",
      externalUrl: "External URL",
      addMaterial: "Add material",
      remove: "Remove",
      criteria: "Judging criteria",
      addCriterion: "Add criterion",
      jury: "Jury assignment",
      judgeEmail: "Judge email",
      assignJudge: "Assign jury member",
      judgeFallback: "Judge",
      awards: "Awards",
      addAward: "Add award",
      noShort: "No short description yet.",
      validationTitle: "Validation",
      fixBefore: "Fix before publication: {items}",
      requiredFilled: "Required publication fields are filled.",
      rejected: "Administrator review rejected this competition. It cannot be published until it is reviewed again.",
      invitations: "Invitation infrastructure",
      invitationsText: "Invitations create records in the invitation table and queue outbound email messages. A real provider can later process the queued messages.",
      individualEmails: "Individual emails",
      teamEmails: "Team emails",
      queueIndividual: "Queue individual invitations",
      queueTeam: "Queue team invitations",
      publishCompetition: "Publish competition",
      back: "Back",
      saveContinue: "Save & continue",
      saveFinal: "Save final draft",
      loading: "Loading...",
    },
    card: {
      noTimer: "No timer",
      save: "Save competition",
      removeSaved: "Remove from saved",
      round: "Round: {current}/{total}",
      participants: "{count} participants",
      pendingReview: "Pending review",
      dayShort: "d",
    },
    statuses: {
      active: "Online",
      draft: "Draft",
      published: "Published",
      finished: "Finished",
      judging: "Judging",
      archived: "Archived",
      registration_open: "Registration open",
      upcoming: "Upcoming",
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
      withdrawn: "Withdrawn",
    },
  },
  uk: {
    splash: {
      starting: "Запускаємо бекенд і базу даних...",
      loadingDemo: "Завантажуємо демо-змагання...",
      waitingApi: "Очікуємо з'єднання з API...",
    },
    header: {
      goHome: "Перейти на головну сторінку",
      search: "Пошук",
      language: "Мова",
      signUp: "Реєстрація",
      signIn: "Вхід",
      profile: "Профіль",
    },
    auth: {
      close: "Закрити",
      signUpTitle: "Реєстрація",
      username: "Ім'я користувача",
      usernamePlaceholder: "Введіть ім'я користувача",
      emailAddress: "Електронна пошта",
      email: "Email",
      emailPlaceholder: "Введіть електронну пошту",
      password: "Пароль",
      passwordPlaceholder: "Пароль",
      createPassword: "Створіть пароль",
      confirmPassword: "Підтвердіть пароль",
      confirmPasswordLabel: "Підтвердження пароля",
      togglePassword: "Показати або приховати пароль",
      showPassword: "Показати",
      hidePassword: "Сховати",
      rolePrompt: "Я хочу приєднатися як:",
      chooseRole: "Виберіть роль облікового запису",
      alreadyHaveAccount: "Вже маєте обліковий запис?",
      logIn: "Увійти",
      welcomeBack: "Раді бачити знову",
      signInCaption: "Увійдіть, щоб керувати збереженими змаганнями, заявками та інструментами організатора.",
      signingIn: "Входимо...",
      signInAction: "Увійти",
      or: "АБО",
      continueOrganizerDemo: "Увійти як демо-організатор",
      continueAdminDemo: "Увійти як демо-адміністратор",
      noAccount: "Ще немає облікового запису?",
      createAccount: "Створити обліковий запис",
      fillRequired: "Заповніть усі обов'язкові поля.",
      passwordsMismatch: "Паролі не збігаються.",
      enterEmailPassword: "Введіть email і пароль.",
    },
    onboarding: {
      title: "Розкажіть більше",
      subtitle: "Оберіть інтереси",
      secondary: "Це можна змінити пізніше у профілі.",
      interests: "Інтереси",
      interestPlaceholder: "Введіть інтерес і натисніть Enter",
      createTeam: "Створити команду після реєстрації",
      continue: "Продовжити",
    },
    roles: {
      organizer: "Організатор",
      participant: "Учасник",
      viewer: "Гість",
      admin: "Адміністратор",
      administrator: "Адміністратор",
      team_member: "Учасник команди",
    },
    options: {
      status: {
        active: "Онлайн",
        draft: "Чернетка",
        published: "Опубліковано",
        finished: "Завершено",
        judging: "Оцінювання",
        archived: "Архів",
        registration_open: "Реєстрація відкрита",
        upcoming: "Незабаром",
        pending: "Очікує",
        approved: "Схвалено",
        rejected: "Відхилено",
        withdrawn: "Відкликано",
        scheduled: "Заплановано",
        closed: "Закрито",
        judged: "Оцінено",
      },
      event_type: {
        online: "Онлайн",
        offline: "Офлайн",
        hybrid: "Гібридний",
      },
      participation_type: {
        individual: "Індивідуальна",
        team: "Командна",
        mixed: "Змішана",
      },
      industry: {
        programming: "Програмування",
        design: "Дизайн",
        robotics: "Робототехніка",
        cybersecurity: "Кібербезпека",
        ai: "ШІ",
        data_science: "Наука про дані",
        web: "Веб",
        mobile: "Мобільна розробка",
      },
      difficulty: {
        beginner: "Початковий",
        intermediate: "Середній",
        advanced: "Просунутий",
        mixed: "Змішаний",
      },
      language: {
        uk: "Українська",
        en: "Англійська",
        pl: "Польська",
        de: "Німецька",
        fr: "Французька",
        es: "Іспанська",
        other: "Інша",
      },
      access_mode: {
        open: "Відкрита реєстрація",
        application: "Розгляд заявок",
        invite_only: "Тільки за запрошенням",
      },
      visibility_mode: {
        public: "Публічний каталог",
        unlisted: "Посилання без каталогу",
        private: "Приватне",
      },
      submission_mode: {
        file_upload: "Завантаження файлу",
        text_answer: "Текстова відповідь",
        repository_link: "Посилання на репозиторій",
        demo_link: "Посилання на демо",
        mixed: "Змішаний",
      },
      material_type: {
        rules: "Правила",
        dataset: "Датасет",
        template: "Шаблон",
        guide: "Гайд",
        other: "Інше",
        file: "Файл",
      },
      review_type: {
        automatic: "Автоматичне",
        jury: "Журі",
        manual: "Ручне",
        peer: "Peer review",
        peer_review: "Peer review",
        participant: "Учасник",
      },
      aggregation: {
        average: "Середнє",
        sum: "Сума",
      },
      visibility: {
        aggregate: "Агреговано",
        open: "Відкрито",
        anonymous: "Анонімно",
      },
    },
    account: {
      currentUser: "Поточний користувач",
      user: "Користувач",
      openProfile: "Відкрити профіль",
      adminPanel: "Адмін-панель",
      switchAccount: "Змінити обліковий запис",
      signOut: "Вийти",
      accountMenu: "Меню облікового запису",
    },
    admin: {
      title: "Адмін-панель",
      subtitle: "Керування обліковими записами, змаганнями, фільтрами лендингу та продуктивністю сервера.",
      tabs: {
        users: "Облікові записи",
        competitions: "Змагання",
        filters: "Фільтри лендингу",
        server: "Сервер",
      },
      actions: "Дії",
      delete: "Видалити",
      settings: {
        title: "Налаштування платформи",
        subtitle: "Керуйте автоматизацією адміністративного прийому заявок організаторів.",
        autoApproveOn: "Автоприйом заявок організаторів: увімкнено",
        autoApproveOff: "Автоприйом заявок організаторів: вимкнено",
      },
      stats: {
        users: "Користувачі",
        activeUsers: "Активні користувачі",
        competitions: "Змагання",
        pendingCompetitions: "Очікують підтвердження",
        activeCompetitions: "Активні змагання",
        draftCompetitions: "Чернетки",
      },
      users: {
        title: "Облікові записи",
        search: "Пошук користувачів",
        allRoles: "Усі ролі",
        user: "Користувач",
        role: "Роль",
        status: "Статус",
        staff: "Staff",
        activity: "Активність",
        active: "Активний",
        inactive: "Неактивний",
        staffYes: "Staff",
        staffNo: "Ні",
        competitions: "Змагань: {count}",
        requests: "Запитів: {count}",
        empty: "Облікові записи не знайдено.",
        confirmDelete: "Видалити обліковий запис \"{name}\"? Цю дію не можна скасувати.",
      },
      competitions: {
        title: "Змагання",
        search: "Пошук змагань",
        allStatuses: "Усі статуси",
        competition: "Змагання",
        status: "Статус",
        approval: "Підтвердження",
        visibility: "Видимість",
        catalog: "Каталог",
        results: "Результати",
        noOrganizer: "Без організатора",
        shown: "Показано",
        hidden: "Приховано",
        frozen: "Заморожено",
        open: "Відкриті",
        empty: "Змагання не знайдено.",
        confirmDelete: "Видалити змагання \"{name}\"? Цю дію не можна скасувати.",
      },
      filters: {
        title: "Фільтри лендингу",
        subtitle: "Редагуйте назви або приховуйте пункти. Значення заблоковані, щоб наявні змагання працювали далі.",
        group: "Група",
        value: "Значення",
        labelEn: "Назва англійською",
        labelUk: "Назва українською",
        order: "Порядок",
        visibility: "Видимість",
        visible: "Видимий",
        hidden: "Прихований",
        empty: "Пункти фільтрів не знайдено.",
        newValue: "Нове значення",
        add: "Додати фільтр",
      },
      server: {
        title: "Продуктивність сервера",
        waiting: "Очікування метрик...",
        refresh: "Оновити",
        uptime: "Час роботи",
        uptimeDays: "{days}д {hours}г",
        uptimeHours: "{hours}г {minutes}хв",
        uptimeMinutes: "{minutes}хв",
        databaseLatency: "Затримка БД",
        processMemory: "Пам'ять процесу",
        memoryUsed: "Використано RAM",
        diskUsed: "Використано диск",
        loadAverage: "Навантаження",
        platform: "Платформа",
        python: "Python",
        django: "Django",
        cpu: "Ядра CPU",
        memory: "Пам'ять",
        disk: "Диск",
      },
      messages: {
        create: "Створити розсилку",
        recent: "Останні розсилки",
        targetRole: "Цільова роль",
        manualRecipients: "Одержувачі вручну",
        allUsers: "Усі активні користувачі",
        competition: "Змагання",
        noCompetition: "Без змагання",
        status: "Статус",
        queued: "У черзі",
        draft: "Чернетка",
        recipientsPlaceholder: "email1@example.com, email2@example.com",
        subject: "Тема",
        body: "Текст",
        general: "Загальна",
        empty: "Розсилок ще немає.",
      },
      saving: "Збереження...",
    },
    filters: {
      title: "Фільтри:",
      groups: {
        status: "Статус",
        event_type: "Тип події",
        participation_type: "Тип участі",
        industry: "Галузь",
        difficulty: "Складність",
        language: "Мова",
        access_mode: "Режим доступу",
      },
      status: "Статус змагання:",
      eventType: "Тип турніру:",
      participationType: "Тип участі:",
      industry: "Галузь:",
      difficulty: "Складність:",
      language: "Мова:",
      reset: "Скинути фільтри",
    },
    landing: {
      loading: "Завантаження...",
    },
    sidebar: {
      recentlyViewed: "Нещодавно переглянуте",
      emptyRecent: "Поки немає нещодавно переглянутих елементів.",
      competitions: "Змагання",
      materials: "Матеріали",
      saved: "Збережене",
      emptySaved: "Поки немає збережених змагань.",
      openCompetition: "Відкрити {name}",
      comments: "{count} коментарів",
    },
    competitionHeader: {
      alreadyParticipating: "Вже бере участь",
      pendingReview: "Очікує розгляду",
      requestRejected: "Заявку відхилено",
      join: "Приєднатися до змагання",
      round: "Раунд: {current}/{total}",
      team: "Команда: {name} - {status}",
      edit: "Редагувати змагання",
    },
    competitionSidebar: {
      round: "Раунд:",
      category: "Категорія:",
      dates: "Дати:",
      difficulty: "Складність:",
      language: "Мова:",
      upcomingEvent: "Найближча подія",
      downloads: "Завантаження",
    },
    joinModal: {
      title: "Приєднатися до змагання",
      description: "Подайте заявку на участь. Залежно від моделі доступу її можуть схвалити автоматично або після перегляду організатором чи адміністратором.",
      individual: "Індивідуальний учасник",
      team: "Командний учасник",
      teamName: "Назва команди",
      teamPlaceholder: "Введіть назву команди або створіть нову",
      note: "Коментар до заявки",
      notePlaceholder: "Необов'язковий коментар для організатора/адміністратора",
      teamRequired: "Для командної участі потрібна назва команди.",
      submitError: "Не вдалося подати заявку на участь.",
      cancel: "Скасувати",
      submitting: "Надсилаємо...",
      joinNow: "Приєднатися",
      submitReview: "Подати на розгляд",
    },
    tabs: {
      active: "Активні змагання",
      trending: "Популярні",
      new: "Нові",
      open_submission: "Відкритий прийом робіт",
      live_stream: "Трансляція",
      completed: "Завершені й архівні",
    },
    detailTabs: {
      overview: "Огляд",
      participants: "Учасники",
      results: "Результати",
      judging: "Оцінювання",
    },
    competitionPage: {
      titleFallback: "Змагання",
      loading: "Завантаження змагання...",
      notFound: "Змагання не знайдено.",
      loadError: "Не вдалося завантажити сторінку змагання.",
      schedulePending: "Розклад уточнюється",
      timerUnavailable: "таймер недоступний",
      categoryFallback: "Змагання",
      difficultyFallback: "Змішана",
      descriptionFallback: "Деталі змагання готує організатор.",
      roundTimer: "Таймер раунду {round}: {time}",
      timer: "Таймер: {time}",
      notConfigured: "не налаштовано",
      you: "Ви",
    },
    overviewTab: {
      liveStream: "Трансляція",
      roundStream: "Трансляція раунду",
      competitionStream: "Трансляція змагання",
      openStream: "Відкрити трансляцію",
      announcements: "Оголошення",
      emptyAnnouncements: "Оголошень поки немає.",
      commentPlaceholder: "Залишити коментар...",
      post: "Опублікувати",
    },
    participantsTab: {
      title: "Учасники",
      empty: "Зареєстрованих учасників поки немає.",
      fallback: "Учасник",
    },
    resultsTab: {
      title: "Результати",
      roundHistory: "Історія раундів",
      round: "Раунд {round}",
      leaderboard: "Рейтинг",
      rank: "Місце",
      name: "Ім'я",
      score: "Бали",
      roundScores: "Оцінки за раунди",
      scored: "Оцінено: {count}",
      scoredCriteria: "Оцінені критерії",
      total: "Разом",
    },
    judgingTab: {
      title: "Оцінювання",
      scoringMode: "Режим оцінювання:",
      aggregation: "Агрегація:",
      visibility: "Видимість:",
      mySubmissions: "Мої подання",
      open: "відкрито",
      closed: "закрито",
      submissionFallback: "Подання",
      noExternalLink: "Немає зовнішнього посилання",
      formTitle: "Назва",
      formDescription: "Опис",
      repositoryUrl: "URL репозиторію",
      demoUrl: "URL демо",
      sending: "Надсилаємо...",
      submitWork: "Подати роботу",
      submissionSent: "Подання відправлено на оцінювання.",
      submissionSaveError: "Не вдалося зберегти подання.",
      submissionUnavailable: "Подання доступні лише схваленим учасникам під час активного раунду.",
      scoreEmpty: "Оцінки з'являться тут після перевірки поданих робіт.",
      scorecard: "Оціночна таблиця",
      mode: "Режим",
      round: "Раунд",
      submission: "Подання",
      noAcceptedForRound: "Для цього раунду немає прийнятих подань.",
      submittedWork: "Подана робота",
      noAcceptedYet: "Для цього раунду ще немає прийнятих подань.",
      criterion: "Критерій",
      max: "Макс.",
      score: "Оцінка",
      comment: "Коментар",
      status: "Статус",
      final: "фінальна",
      draft: "чернетка",
      new: "нова",
      clear: "Очистити",
      saving: "Збереження...",
      saveDraft: "Зберегти чернетку",
      finalize: "Фіналізувати",
      scoresFinalized: "Оцінки фіналізовано.",
      draftScoresSaved: "Чернетки оцінок збережено.",
      scoresSaveError: "Не вдалося зберегти оцінки.",
      scoreRemoved: "Оцінку видалено.",
      scoreRemoveError: "Не вдалося видалити оцінку.",
      judgeInvitations: "Запрошення судді",
      acceptedAssignments: "Прийнято: {count}",
      waitingForResponse: "Очікує відповіді",
      allRounds: "Усі раунди",
      acceptInvite: "Прийняти",
      declineInvite: "Відхилити",
      inviteAccepted: "Запрошення прийнято.",
      inviteDeclined: "Запрошення відхилено.",
      inviteResponseError: "Не вдалося зберегти відповідь на запрошення.",
      acceptInviteToScore: "Прийміть запрошення судді перед оцінюванням.",
      judgingWindowClosed: "Матеріали для суддів доступні лише у вікно оцінювання.",
      repository: "Репозиторій",
      demo: "Демо",
      file: "Файл",
    },
    profile: {
      organized: "організовано",
      pending: "Очікує",
      archived: "Архів",
      badges: "беджі",
      certificates: "сертифікати",
      judgeAssignments: "призначення судді",
      organizerStats: "Статистика організатора",
      participantStats: "Статистика учасника",
      judgeWork: "Робота судді",
      judgeScores: "Оцінок: {count}, фіналізовано: {final}",
      organizerTools: "Інструменти організатора",
      createCompetitionTitle: "Створити нове змагання",
      createCompetitionText: "Підготуйте базову інформацію, раунди, дедлайни, ролі журі та статус публікації в одному робочому просторі.",
      createCompetition: "Створити змагання",
      organizedCompetitions: "Мої організовані змагання",
      noOrganized: "Організованих змагань немає.",
      step: "Крок {step}",
      approval: "схвалення",
      myTeams: "Мої команди",
      captain: "Капітан: {name}",
      notAssigned: "не призначено",
      you: "ви",
      makeCaptain: "Зробити капітаном",
      remove: "Видалити",
      captainNote: "Дозволений лише один капітан. Права капітана можна передати іншому учаснику команди.",
      noCompetitions: "У цій секції поки немає змагань.",
      latest: "Останнє",
      achievement: "Особисте досягнення",
      noBadges: "Беджів поки немає.",
      noCertificates: "Сертифікатів поки немає.",
      registrationRequests: "Заявки на реєстрацію",
      creationRequests: "Заявки на створення змагань",
      myApplications: "Мої заявки в очікуванні",
      noPending: "Заявок в очікуванні немає.",
      approve: "Схвалити",
      reject: "Відхилити",
      editProfile: "Редагувати профіль",
      profilePhoto: "Фото профілю",
      uploadPhoto: "Завантажити фото профілю",
      displayName: "Ім'я для показу",
      email: "Email",
      status: "Статус",
      organization: "Організація",
      country: "Країна",
      skills: "Навички",
      interests: "Інтереси",
      bio: "Біо",
      saveProfile: "Зберегти профіль",
      overview: "Огляд",
      archivedTab: "Архів",
      myCompetitions: "Мої змагання",
      loading: "Завантаження профілю...",
      goHome: "Перейти на головну",
      search: "Пошук",
      nameFallback: "Ім'я",
      close: "Закрити",
      edit: "Редагувати",
      profileSections: "Секції профілю",
      registeredCompetitions: "Зареєстровані змагання",
      noRegistered: "Ви ще не зареєстровані на активні або майбутні змагання.",
      archivedCompetitions: "Архівні змагання",
      noArchived: "Архівних змагань поки немає.",
      viewerProfile: "Профіль гостя",
      viewerText: "Роль гостя залишає робочий простір простим: нещодавні перегляди та збережені публічні змагання.",
      savedCompetitions: "Збережені змагання",
      noSaved: "Збережених змагань поки немає.",
      recentlyViewed: "Нещодавно переглянуте",
      latestNotifications: "Останні сповіщення",
      noNotifications: "Сповіщень для цього облікового запису поки немає.",
      personalMaterials: "Особисті матеріали",
      material: "Матеріал",
      file: "Файл",
    },
    builder: {
      steps: {
        basics: "Основи",
        basicsHint: "Картка, фільтри каталогу та публічна ідентичність",
        format: "Формат і доступ",
        formatHint: "Реєстрація, розгляд, команди та видимість",
        schedule: "Розклад і раунди",
        scheduleHint: "Реєстрація, етапи змагання та часові вікна",
        submissions: "Подання й оцінювання",
        submissionsHint: "Правила подання, критерії та нагороди",
        publish: "Публікація",
        publishHint: "Перегляд, валідація та запрошення",
      },
      defaults: {
        untitled: "Нове змагання",
        round: "Раунд {number}",
        quality: "Якість",
        winner: "Переможець",
        invitedTeam: "Запрошена команда",
        newCriterion: "Новий критерій",
        specialAward: "Спеціальна нагорода",
      },
      status: {
        saving: "Зберігаємо чернетку...",
        saved: "Чернетку збережено",
        notSaved: "Чернетку не збережено",
        published: "Змагання опубліковано",
        notPublished: "Змагання не опубліковано",
        invitesQueued: "Запрошення додано до черги повідомлень",
        invitesFailed: "Запрошення не додано до черги",
        judgeAssigned: "Члена журі призначено",
        judgeFailed: "Члена журі не призначено",
        materialUploaded: "Матеріал завантажено",
        materialFailed: "Матеріал не завантажено",
        materialRemoved: "Матеріал видалено",
        materialRemoveFailed: "Матеріал не видалено",
      },
      validation: {
        endAfterStart: "Кінець змагання має бути пізніше початку.",
        registrationBeforeStart: "Реєстрація не може починатися після старту змагання.",
        registrationEndBeforeStart: "Реєстрація має завершитися не пізніше старту змагання.",
        registrationEndAfterStart: "Кінець реєстрації має бути пізніше її початку.",
        judgingAfterCompetition: "Оцінювання не може починатися до завершення змагання.",
        judgingEndAfterStart: "Кінець оцінювання має бути пізніше його початку.",
        resultsAfterJudging: "Результати не можна публікувати до завершення оцінювання.",
        roundWithinWindow: "{label}: раунд має починатися в межах змагання.",
        roundEndWithinWindow: "{label}: раунд має завершуватися в межах змагання.",
        roundEndAfterStart: "{label}: кінець раунду має бути пізніше початку.",
        nextRoundAfterPrevious: "{label}: наступний раунд має починатися після завершення попереднього.",
        nextRoundEndAfterPrevious: "{label}: наступний раунд має завершуватися після завершення попереднього.",
        title: "назва змагання",
        shortDescription: "короткий опис",
        competitionEnd: "кінець змагання",
        oneRound: "принаймні один раунд",
        roundEnd: "час завершення раунду",
        sharingOrInvitations: "посилання для поширення або запрошення",
      },
      topbarProfile: "Профіль",
      constructor: "Конструктор змагання",
      saveDraft: "Зберегти чернетку",
      stepOf: "Крок {step} з 5",
      newCompetition: "Нове змагання",
      heroText: "Одна чернетка оновлюється протягом усього налаштування. Ті самі поля формують фільтри каталогу, картки, блоки профілю та правила участі.",
      title: "Назва",
      categoryIndustry: "Категорія / галузь",
      categoryNote: "Використовується у фільтрах каталогу",
      eventType: "Тип події",
      difficulty: "Складність",
      language: "Мова",
      languageNote: "Використовується у фільтрах лендингу",
      shortDescription: "Короткий опис",
      fullDescription: "Повний опис",
      coverImage: "URL обкладинки",
      bannerImage: "URL банера",
      registrationModel: "Модель реєстрації та розподілу",
      openRegistrationText: "Join одразу створює схвалену участь.",
      applicationReviewText: "Join створює заявку, доки її не схвалить організатор або адміністратор.",
      inviteOnlyText: "Користувачі приєднуються через запрошення організатора; приховані змагання можуть використовувати приватні посилання.",
      individualText: "Кожен учасник подає роботу самостійно.",
      teamText: "Зареєстровані учасники приєднуються до команд або створюють їх; організатори лише керують змаганням.",
      mixedText: "Дозволена і індивідуальна, і командна участь.",
      visibility: "Видимість",
      showCatalog: "Показувати в каталозі",
      allowSharing: "Дозволити посилання для поширення",
      externalRegistration: "Зовнішня реєстрація",
      minTeam: "Мін. розмір команди",
      maxTeam: "Макс. розмір команди",
      participantInvites: "Запрошення від учасників",
      organizerAssignment: "Призначення команд організатором",
      scheduleRounds: "Розклад і раунди",
      scheduleText: "Статус змагання, таймери й вкладки каталогу формуються з цих часових вікон і дат раундів.",
      registrationStarts: "Початок реєстрації",
      registrationEnds: "Кінець реєстрації",
      competitionStarts: "Початок змагання",
      competitionStartsNote: "Необов'язково: якщо порожньо, змагання стартує при публікації.",
      competitionEnds: "Кінець змагання",
      judgingStarts: "Початок оцінювання",
      judgingEnds: "Кінець оцінювання",
      resultsPublic: "Публікація результатів",
      rounds: "Раунди",
      delete: "Видалити",
      roundTitle: "Назва раунду",
      roundTimeTitle: "Необов'язково для першого/наступного послідовного раунду; порожній початок визначається при публікації.",
      submissionRequired: "Потрібне подання",
      showVideo: "Показувати відеотрансляцію",
      streamLabel: "Назва трансляції, напр. брифінг раунду",
      streamUrl: "URL трансляції: YouTube, Vimeo або Twitch",
      streamHint: "Вставте звичайне посилання на трансляцію. YouTube, youtu.be, Vimeo, Twitch channel/video автоматично конвертуються у вбудований плеєр. Не вставляйте iframe-код.",
      roundDescription: "Опис раунду",
      addRound: "Додати раунд",
      submissionSettings: "Налаштування подань",
      submissionMode: "Режим подання",
      maxFileSize: "Макс. розмір файлу, МБ",
      maxSubmissions: "Макс. кількість подань",
      repositoryRequired: "Репозиторій обов'язковий",
      demoRequired: "Демо обов'язкове",
      materials: "Матеріали змагання",
      materialTitle: "Назва матеріалу",
      materialPlaceholder: "Правила, стартовий набір, датасет",
      materialType: "Тип матеріалу",
      uploadFile: "Завантажити файл",
      externalUrl: "Зовнішній URL",
      addMaterial: "Додати матеріал",
      remove: "Видалити",
      criteria: "Критерії оцінювання",
      addCriterion: "Додати критерій",
      jury: "Призначення журі",
      judgeEmail: "Email судді",
      assignJudge: "Призначити члена журі",
      judgeFallback: "Суддя",
      awards: "Нагороди",
      addAward: "Додати нагороду",
      noShort: "Короткого опису ще немає.",
      validationTitle: "Валідація",
      fixBefore: "Виправте перед публікацією: {items}",
      requiredFilled: "Обов'язкові поля для публікації заповнені.",
      rejected: "Адміністратор відхилив це змагання. Його не можна опублікувати до повторного розгляду.",
      invitations: "Інфраструктура запрошень",
      invitationsText: "Запрошення створюють записи в таблиці запрошень і додають email-повідомлення до черги. Реальний провайдер зможе обробити ці повідомлення пізніше.",
      individualEmails: "Email індивідуальних учасників",
      teamEmails: "Email команд",
      queueIndividual: "Додати індивідуальні запрошення до черги",
      queueTeam: "Додати командні запрошення до черги",
      publishCompetition: "Опублікувати змагання",
      back: "Назад",
      saveContinue: "Зберегти й продовжити",
      saveFinal: "Зберегти фінальну чернетку",
      loading: "Завантаження...",
    },
    card: {
      noTimer: "Без таймера",
      save: "Зберегти змагання",
      removeSaved: "Прибрати зі збережених",
      round: "Раунд: {current}/{total}",
      participants: "{count} учасників",
      pendingReview: "Очікує розгляду",
      dayShort: "д",
    },
    statuses: {
      active: "Онлайн",
      draft: "Чернетка",
      published: "Опубліковано",
      finished: "Завершено",
      judging: "Оцінювання",
      archived: "Архів",
      registration_open: "Реєстрація відкрита",
      upcoming: "Незабаром",
      pending: "Очікує",
      approved: "Схвалено",
      rejected: "Відхилено",
      withdrawn: "Відкликано",
    },
  },
};

function resolvePath(source, path) {
  return path.split(".").reduce((value, key) => {
    if (value && Object.prototype.hasOwnProperty.call(value, key)) {
      return value[key];
    }
    return undefined;
  }, source);
}

function interpolate(template, params) {
  return String(template).replace(/\{(\w+)\}/g, (_, key) => {
    if (Object.prototype.hasOwnProperty.call(params, key)) {
      return params[key];
    }
    return `{${key}}`;
  });
}

function detectInitialLanguage() {
  try {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (supportedLanguages.some((item) => item.code === stored)) return stored;
  } catch {
    // Ignore storage access errors.
  }

  const browserLanguage = navigator.language || "";
  return browserLanguage.toLowerCase().startsWith("uk") ? "uk" : "en";
}

const LanguageContext = createContext(null);

function normalizeLanguage(value) {
  return supportedLanguages.some((item) => item.code === value) ? value : "";
}

function writeStoredLanguage(nextLanguage) {
  try {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage);
  } catch {
    // Ignore storage access errors.
  }
}

export function LanguageProvider({ children }) {
  const { user, loading, updateProfile } = useAuth();
  const [language, setLanguageState] = useState(detectInitialLanguage);

  const setLanguage = useCallback((nextLanguage, options = {}) => {
    const normalized = normalizeLanguage(nextLanguage) || "en";
    setLanguageState(normalized);
    writeStoredLanguage(normalized);

    if (options.persistToAccount !== false && user && user.language !== normalized) {
      updateProfile({ language: normalized });
    }
  }, [user, updateProfile]);

  useEffect(() => {
    if (loading) return;

    const accountLanguage = normalizeLanguage(user?.language);
    if (accountLanguage) {
      if (accountLanguage !== language) {
        setLanguageState(accountLanguage);
      }
      writeStoredLanguage(accountLanguage);
      return;
    }

    if (user) {
      updateProfile({ language });
    }
  }, [language, loading, updateProfile, user]);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language, setLanguage]);

  const value = useMemo(() => {
    const t = (key, params = {}) => {
      const translated =
        resolvePath(dictionaries[language], key) ??
        resolvePath(dictionaries.en, key) ??
        params.defaultValue ??
        key;
      return interpolate(translated, params);
    };

    return {
      language,
      setLanguage,
      supportedLanguages,
      t,
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
