# Generated by Django 5.1.6 on 2026-03-15 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('full_description', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('banner_image', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('registration_open', 'Registration Open'), ('active', 'Active'), ('judging', 'Judging'), ('finished', 'Finished'), ('archived', 'Archived')], db_index=True, max_length=32)),
                ('event_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], db_index=True, max_length=16)),
                ('participation_type', models.CharField(choices=[('team', 'Team'), ('individual', 'Individual')], db_index=True, max_length=16)),
                ('industry', models.CharField(choices=[('programming', 'Programming'), ('design', 'Design'), ('robotics', 'Robotics'), ('cybersecurity', 'Cybersecurity')], db_index=True, max_length=32)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed')], db_index=True, max_length=32)),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('total_rounds', models.PositiveIntegerField(default=1)),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('is_live_stream_enabled', models.BooleanField(default=False)),
                ('is_online_now', models.BooleanField(default=False)),
                ('registration_open', models.BooleanField(default=False)),
                ('submissions_open', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('trending_score', models.FloatField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('timer_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_announcements', to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='landing.competition')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionAnnouncementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='landing.competitionannouncement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_announcement_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionJudgingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], default='individual', max_length=16)),
                ('label', models.CharField(max_length=255)),
                ('value', models.FloatField(default=0)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_metrics', to='landing.competition')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionLeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0)),
                ('entry_type', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], default='individual', max_length=16)),
                ('round_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='landing.competition')),
            ],
            options={
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('rules', 'Rules'), ('dataset', 'Dataset'), ('template', 'Template'), ('guide', 'Guide'), ('other', 'Other')], default='other', max_length=32)),
                ('url', models.URLField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='landing.competition')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('team', 'Team'), ('observer', 'Observer'), ('judge', 'Judge'), ('organizer', 'Organizer')], default='participant', max_length=32)),
                ('is_active_now', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_entries', to='landing.competition')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionPlannedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_kind', models.CharField(choices=[('announcement', 'Announcement'), ('round_start', 'Round Start'), ('round_end', 'Round End'), ('judging_start', 'Judging Start'), ('judging_end', 'Judging End'), ('results', 'Results'), ('other', 'Other')], default='other', max_length=32)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_events', to='landing.competition')),
            ],
            options={
                'ordering': ['starts_at', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionRoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('leader_name', models.CharField(max_length=255)),
                ('top_score', models.FloatField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='landing.competition')),
            ],
            options={
                'ordering': ['round_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('team', 'Team'), ('observer', 'Observer')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='landing.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('competition', 'user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='UserCompetitionWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_live', models.BooleanField(default=True)),
                ('watch_rounds', models.BooleanField(default=True)),
                ('watch_updates', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='landing.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_competitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'competition')},
            },
        ),
        migrations.CreateModel(
            name='UserSavedCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='landing.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_competitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'competition')},
            },
        ),
    ]
