# Generated by Django 5.1.6 on 2026-05-03 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_competition_teams_and_participation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='access_mode',
            field=models.CharField(choices=[('open', 'Open registration'), ('application', 'Application review'), ('invite_only', 'Invite only')], db_index=True, default='application', max_length=32),
        ),
        migrations.AddField(
            model_name='competition',
            name='allow_external_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='allow_organizer_team_assignment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='allow_sharing_link',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='allow_user_team_invites',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='completion_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='judging_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='judging_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='language',
            field=models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English'), ('pl', 'Polish'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish'), ('other', 'Other')], db_index=True, default='uk', max_length=16),
        ),
        migrations.AddField(
            model_name='competition',
            name='max_team_size',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='competition',
            name='min_team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competition',
            name='publish_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='registration_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='registration_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='results_public_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='setup_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competition',
            name='show_in_catalog',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='visibility_mode',
            field=models.CharField(choices=[('public', 'Public catalog'), ('unlisted', 'Unlisted link'), ('private', 'Private')], db_index=True, default='public', max_length=32),
        ),
        migrations.AlterField(
            model_name='competition',
            name='participation_type',
            field=models.CharField(choices=[('team', 'Team'), ('individual', 'Individual'), ('mixed', 'Mixed')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='competitionjoinrequest',
            name='role',
            field=models.CharField(choices=[('participant', 'Participant'), ('team_member', 'Team member')], max_length=32),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='role',
            field=models.CharField(choices=[('participant', 'Participant'), ('team_member', 'Team member'), ('judge', 'Judge'), ('organizer', 'Organizer')], default='participant', max_length=32),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=32),
        ),
        migrations.CreateModel(
            name='CompetitionAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('place', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_certificate', models.BooleanField(default=True)),
                ('issue_badge', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='landing.competition')),
            ],
            options={
                'ordering': ['place', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('target_type', models.CharField(choices=[('individual', 'Individual participant'), ('team', 'Team')], default='individual', max_length=32)),
                ('team_name', models.CharField(blank=True, max_length=255)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='draft', max_length=32)),
                ('message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='landing.competition')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_competition_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('competition', 'email', 'target_type', 'team_name')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionJudgingCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judging_mode', models.CharField(choices=[('manual', 'Manual judging'), ('automatic', 'Automatic judging'), ('mixed', 'Mixed judging'), ('public_voting', 'Public voting')], default='manual', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('max_score', models.PositiveIntegerField(default=10)),
                ('weight', models.FloatField(default=1.0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_criteria', to='landing.competition')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('submission_required', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='landing.competition')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionSubmissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_mode', models.CharField(choices=[('file_upload', 'File upload'), ('text_answer', 'Text answer'), ('repository_link', 'Repository link'), ('demo_link', 'Demo link'), ('mixed', 'Mixed')], default='mixed', max_length=32)),
                ('allowed_file_types', models.JSONField(blank=True, default=list)),
                ('max_file_size_mb', models.PositiveIntegerField(default=25)),
                ('max_submissions', models.PositiveIntegerField(default=1)),
                ('repository_url_required', models.BooleanField(default=False)),
                ('demo_url_required', models.BooleanField(default=False)),
                ('description_required', models.BooleanField(default=True)),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_settings', to='landing.competition')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('platform', 'Platform notification')], default='email', max_length=32)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='draft', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='landing.competition')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='landing.competitioninvitation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to='landing.competitionmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'material')},
            },
        ),
    ]
