# Generated by Django 5.1.6 on 2026-05-05 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_file_upload_content_and_material_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='automatic_judging_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='judging_aggregation',
            field=models.CharField(choices=[('average', 'Average'), ('sum', 'Sum')], default='average', max_length=16),
        ),
        migrations.AddField(
            model_name='competition',
            name='judging_visibility',
            field=models.CharField(choices=[('aggregate', 'Aggregate scores only'), ('open', 'Show judge scores'), ('anonymous', 'Anonymous judge scores')], default='aggregate', max_length=16),
        ),
        migrations.AddField(
            model_name='competition',
            name='manual_judging_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='peer_review_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='results_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitionround',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('closed', 'Closed'), ('judged', 'Judged')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='competitionsubmissionsettings',
            name='submission_policy',
            field=models.CharField(choices=[('single', 'Single submission'), ('latest', 'Latest submission wins'), ('multiple', 'Multiple submissions')], default='single', max_length=16),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('upcoming', 'Upcoming'), ('registration_open', 'Registration Open'), ('active', 'Active'), ('judging', 'Judging'), ('finished', 'Finished'), ('archived', 'Archived')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='competitionjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='competitionjudgingcriterion',
            name='judging_mode',
            field=models.CharField(choices=[('manual', 'Manual judging'), ('automatic', 'Automatic judging'), ('peer_review', 'Peer review'), ('mixed', 'Mixed judging'), ('public_voting', 'Public voting')], default='manual', max_length=32),
        ),
        migrations.AlterField(
            model_name='competitionmaterial',
            name='material_type',
            field=models.CharField(choices=[('file', 'File'), ('link', 'Link'), ('video', 'Video'), ('repository', 'Repository'), ('rules', 'Rules'), ('dataset', 'Dataset'), ('template', 'Template'), ('guide', 'Guide'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.CreateModel(
            name='CompetitionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('repository_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('validated', 'Validated'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('locked', 'Locked')], db_index=True, default='created', max_length=16)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='landing.competition')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_submissions', to='landing.userfile')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='landing.competitionparticipant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='landing.competitionround')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_submissions', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='landing.competitionteam')),
            ],
            options={
                'ordering': ['round__sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionJudgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('manual', 'Manual judge'), ('peer_review', 'Peer reviewer'), ('automatic', 'Automatic evaluator')], db_index=True, default='manual', max_length=16)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], db_index=True, default='invited', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='landing.competition')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_judge_assignments', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_judge_assignments', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='landing.competitionround')),
            ],
            options={
                'ordering': ['competition', 'round__sort_order', 'judge_id'],
                'unique_together': {('competition', 'round', 'judge', 'assignment_type')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual judge'), ('peer_review', 'Peer review')], db_index=True, max_length=16)),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comment', models.TextField(blank=True)),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='landing.competition')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='landing.competitionjudgingcriterion')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_scores', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='landing.competitionround')),
                ('subject_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_scores', to='landing.competitionparticipant')),
                ('subject_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_scores', to='landing.competitionteam')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='landing.competitionsubmission')),
            ],
            options={
                'ordering': ['round__sort_order', 'subject_team_id', 'subject_participant_id', 'criterion__sort_order', 'id'],
                'indexes': [models.Index(fields=['competition', 'round', 'review_type'], name='landing_com_competi_46508d_idx'), models.Index(fields=['competition', 'subject_participant'], name='landing_com_competi_544724_idx'), models.Index(fields=['competition', 'subject_team'], name='landing_com_competi_827200_idx')],
            },
        ),
    ]
