# Generated by Django 5.1.6 on 2026-05-05 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_competition_automatic_judging_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='competitionscore',
            constraint=models.UniqueConstraint(condition=models.Q(('submission__isnull', False)), fields=('competition', 'round', 'criterion', 'judge', 'review_type', 'submission'), name='uniq_score_by_submission'),
        ),
        migrations.AddConstraint(
            model_name='competitionscore',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_participant__isnull', False), ('submission__isnull', True)), fields=('competition', 'round', 'criterion', 'judge', 'review_type', 'subject_participant'), name='uniq_score_by_participant'),
        ),
        migrations.AddConstraint(
            model_name='competitionscore',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_team__isnull', False), ('submission__isnull', True)), fields=('competition', 'round', 'criterion', 'judge', 'review_type', 'subject_team'), name='uniq_score_by_team'),
        ),
    ]
